      subroutine bcast_cov
      use mpidat
      use sizes
      use atoms
      use bndpot
      use bndstr
      use angbnd
      use angpot
      use kurybr
      use urey
      use urypot
      use limits
      use potent
      use strbnd
      implicit none
      include 'mpif.h'
      integer ierr
          call mpi_bcast(nbond,1,mpi_integer,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(ibnd,2*nbond,mpi_integer,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(bk,nbond,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(bl,nbond,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(cbnd,1,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(qbnd,1,mpi_real8,master,
     &   mpi_comm_world,ierr) 
          call mpi_bcast(bndunit,1,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(bndtyp,8,mpi_character,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(use_bond,1,mpi_logical,master,
     &   mpi_comm_world,ierr)

          call mpi_bcast(use_angle,1,mpi_logical,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(nangle,1,mpi_integer,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(iang,4*nangle,mpi_integer,master,
     &   mpi_comm_world,ierr) 
          call mpi_bcast(anat,nangle,mpi_real8,master,
     &   mpi_comm_world,ierr)          
          call mpi_bcast(ak,nangle,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(afld,nangle,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(cang,1,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(qang,1,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(pang,1,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(sang,1,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(angunit,1,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(angtyp,8*nangle,mpi_character,master,
     &   mpi_comm_world,ierr)          

          call mpi_bcast(use_strbnd,1,mpi_logical,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(use_urey,1,mpi_logical,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(use_angang,1,mpi_logical,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(use_opbend,1,mpi_logical,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(use_opdist,1,mpi_logical,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(use_improp,1,mpi_logical,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(use_imptor,1,mpi_logical,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(use_tors,1,mpi_logical,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(use_pitors,1,mpi_logical,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(use_strtor,1,mpi_logical,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(use_angtor,1,mpi_logical,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(use_tortor,1,mpi_logical,master,
     &   mpi_comm_world,ierr)


          call mpi_bcast(nstrbnd,1,mpi_integer,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(isb,3*nangle,mpi_integer,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(sbk,2*nangle,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(stbnunit,1,mpi_real8,master,
     &   mpi_comm_world,ierr)

          call mpi_bcast(nurey,1,mpi_integer,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(iury,3*nangle,mpi_integer,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(ul,nangle,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(uk,nangle,mpi_real8,master,
     &   mpi_comm_world,ierr)
           call mpi_bcast(cury,1,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(qury,1,mpi_real8,master,
     &   mpi_comm_world,ierr)
          call mpi_bcast(ureyunit,1,mpi_real8,master,
     &   mpi_comm_world,ierr)
      return
      end
